name: lasergun_client_dart
description: A Lasergun server connection library.
version: 1.0.0
homepage: https://github.com/taworn-ta7/examples.lasergun

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  logging: ^1.0.2
  json_annotation: ^4.4.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
